### PR TITLE
chore: upgrade actions

### PR DESCRIPTION
**Pull request by fgreinacher**

### CODE REVIEW

**Comment by fgreinacher** [comment]
@mstruebing Let's upgrade to Node 16 first :)

**Review by mstruebing — COMMENTED** [review]
Can you adjust the `on` property so that this workflow will run on pull requests too?

**Comment by fgreinacher** [comment]
Just noticed that too :)

**Comment by fgreinacher** [comment]
Upgraded `@zeit/ncc` to get https://github.com/vercel/ncc/pull/868.

Also pinned Node version so that this does not break randomly in the future :)

**Pull request merged**
