### PR TITLE
fix: allow Node.js versions >= 18

### PR DESCRIPTION
**Pull request by theoludwig**
Hello!

Since https://github.com/editorconfig-checker/editorconfig-checker.javascript/commit/1bc42852f461a33df6aee12ac920afbf841ded03, only Node.js v18 is allowed.
Whereas, this package is also working with Node.js v20 for example.

When running `npm install`:
```sh
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'editorconfig-checker@5.1.0',
npm WARN EBADENGINE   required: { node: '^18.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.3.0', npm: '9.7.1' }
npm WARN EBADENGINE }
```

Is it possible to merge this PR, and release it quickly as a patch version, 5.1.1, thanks! :smile:

### CODE REVIEW

**Comment by theoludwig** [comment]
cc @mstruebing

**Comment by mstruebing** [comment]
Anyone interesting in fixing this?

**Review by mstruebing — APPROVED** [review]
Upps, I'm sorry - I thought this was an issue not a PR ...

**Comment by nsballmann** [comment]
@mstruebing When do you plan on releasing this as 5.1.1 or similar?

**Comment by mstruebing** [comment]
I can do it today, sorry for the delay.

**Comment by mstruebing** [comment]
It's out there @nsballmann https://www.npmjs.com/package/editorconfig-checker/v/5.1.1

**Pull request merged**
